import '@/app/globals.css';
import type { Metadata } from 'next';
import Navbar from '@/components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function NewStoryLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='p-10'>
        <Navbar />
        <div className='max-w-5xl mx-auto'>{children}</div>
      </body>
    </html>
  );
}
