import '@/app/globals.css';
import type { Metadata } from 'next';
import Navbar from '@/components/navbar';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function StoriesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='py-10 px-[72px]'>
        <Toaster />
        <Navbar />
        <div className='max-w-xl md:max-w-5xl mx-auto'>{children}</div>
      </body>
    </html>
  );
}
