import Navbar from '@/components/navbar';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='max-w-md md:max-w-xl lg:max-w-3xl mx-auto'>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
